*Pandas* is a fast, powerful, flexible, and easy to use open source data analysis and manipulation tool, built on top of Python. Pandas is best known for for the extensive set of features that it provides:

- Selecting, and filtering rows and columns
- Proper handling of missing data
- Applying operations across rows and columns
- Merging data sets together
- Grouping and applying aggregation functions

*Pandas* offers two classes **`Dataframe`** and **`Series`**. A pandas `Series` can simply be thought of a 1-dimensional data where each values is associated with an index (label). The `DataFrame` can be thought of as the extension of `Series` to 2D, where each values has a corresponding column name and index.

In [78]:
import numpy as np
import pandas as pd
tempArr = np.arange(0, 6)
tempSeries = pd.Series(tempArr)
print(tempSeries)

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


In [82]:
tempIndices = list('abcedf')
tempSeries = pd.Series(tempArr, index=tempIndices)
print(tempSeries)

a    0
b    1
c    2
e    3
d    4
f    5
dtype: int64


In [83]:
tempSeries.index = list('fedcbe')
print(tempSeries)

f    0
e    1
d    2
c    3
b    4
e    5
dtype: int64


In [84]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


In [81]:
tempArrEven = np.arange(0, 10, 2)
tempArrOdd = np.arange(1, 11, 2)
tempDataFrame = pd.DataFrame(np.array([tempArrEven, tempArrOdd]).T)
print(tempDataFrame)

   0  1
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9


In [69]:
print(tempDataFrame)

NameError: name 'tempDataFrame' is not defined

In [33]:
tempArrOdd

array([0, 2, 4, 6, 8])

In [34]:
tempArrEven

array([1, 3, 5, 7, 9])

In [49]:
tempArrEven.reshape(-1,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [75]:
print(pd.DataFrame(tempArr).shape)
print(pd.Series(tempArr).shape)

(6, 1)
(6,)


In [66]:
pd.DataFrame(tempArrEven).shape

(5, 1)

In [21]:
# Solution
ser1 = pd.Series(tempList)
ser2 = pd.Series(tempArr)
ser3 = pd.Series(tempDict)

In [25]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [29]:
df.iloc[:,:5].head()

Manufacturer    Model     Type  Min.Price  Price
0        Acura  Integra    Small       12.9   15.9
1          NaN   Legend  Midsize       29.2   33.9
2         Audi       90  Compact       25.9   29.1
3         Audi      100  Midsize        NaN   37.7
4          BMW     535i  Midsize        NaN   30.0

In [18]:
ser3

a    0
b    1
c    2
e    3
d    4
f    5
dtype: int64